#
# Makefile for the KXTI9 Sensor driver
#

sensor_kxti9-objs  := kxti9.o
# ASUS Engineer Mode for factory tools testing by Darren added [2012/07/19]
obj-$(CONFIG_ASUS_ENGINEER_MODE)	+= asustag_kxti9.o
obj-$(CONFIG_WMT_SENSOR_KXTI9)		+= sensor_kxti9.o
