# Copyright (c) 2012, ASUSTek, Inc. All Rights Reserved.
# Written by wade chen Wade1_Chen@asus.com
# 
obj-$(CONFIG_ASUS_NCT7717U_THERMAL)   	+= nct7717u.o
obj-$(CONFIG_ASUS_NCT7717U_THERMAL)   	+= nct7717u_proc_fs.o
obj-$(CONFIG_ASUS_NCT7717U_THERMAL)   	+= nct7717u_proc_fs_asustag.o
